# Generated by Django 3.2.5 on 2021-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название курса', models.CharField(max_length=255)),
                ('Описание', models.TextField()),
                ('Значок', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название поста', models.CharField(max_length=255)),
                ('Содержание поста', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=255)),
                ('Фамилия', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('codeforces', models.CharField(max_length=255)),
                ('Фото', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название задания', models.CharField(max_length=255)),
                ('Описание', models.TextField()),
            ],
        ),
    ]
