# Generated by Django 3.2.5 on 2021-12-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='main_site.Student'),
        ),
        migrations.AddField(
            model_name='courseentry',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_site.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Пользователь',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentInCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.student')),
            ],
        ),
    ]
