# Generated by Django 3.2.5 on 2021-12-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mark',
            field=models.TextField(default='0', verbose_name='Оценка'),
        ),
    ]
